name: social_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  awesome_notifications: ^0.9.3+1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.13.2
  conditional_builder_null_safety: ^0.0.6
  dio: ^5.0.1
  firebase_auth: ^4.14.1
  firebase_core: ^2.21.0
  firebase_messaging: ^14.9.1
  firebase_storage: ^11.5.5
  firebase_storage_web: ^3.6.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  image_picker: ^1.0.4
  shared_preferences: ^2.0.18
  smooth_page_indicator: ^1.1.0
  uuid: ^4.4.0
  video_player: ^2.8.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  # fonts:
  #   - family: louis
  #     fonts:
  #       - asset: assets/fonts/Louis.ttf
  fonts:
    - family: Jannah
      fonts:
        - asset: assets/fonts/jannah.ttf
          weight: 700
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
